### PR TITLE
liblightdm-qt: mark class PowerInterface as exported

### PR DESCRIPTION
**Pull request by corsac-s**
fix build when using -fvisibility=hidden to stop exporting all symbols

### CODE REVIEW

**Comment by corsac-s** [comment]
Sorry for the mess with PR #22. Not sure if you prefer multiple PR or if you prefer to cherry-pick/merge stuff yourself.

**Comment by robert-ancell** [comment]
This was done in PR #20, right? Should there be a PR to use -fvisibility=hidden?

**Comment by robert-ancell** [comment]
Multiple PRs are generally my preference, though I appreciate it gets a bit harder when changes depend on eachother. Happy to cherry-pick when appropriate

**Comment by robert-ancell** [comment]
Oh, now I understand - yes, a PR for each release makes it easier for me.

**Comment by corsac-s** [comment]
On Tue, 2018-05-22 at 14:36 -0700, Robert Ancell wrote:
> Should there be a PR to use -fvisibility=hidden?

I can do that yes
-- 
Yves-Alexis

**Comment by corsac-s** [comment]
On Tue, 2018-05-22 at 14:38 -0700, Robert Ancell wrote:
> Oh, now I understand - yes, a PR for each release makes it easier for me.

Ok, will do that for other supported releases.
-- 
Yves-Alexis

**Pull request merged**
